server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leezhuang96/spring-cloud-base.git
          search-paths: config
          username: leezhuang96@gmail.com
          password: lz199696
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/