server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-adddress: true
feign:
  hystrix:
    enabled: true #是否开启熔断器
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

#http://localhost:8050/actuator/hystrix.stream
#http://localhost:8050/hystrix